apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: centos
  name: centos
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: centos
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: centos
    spec:
      containers:
      - command:
        - /bin/bash
        - -c
        - sleep 6500000
        image: centos:7
        imagePullPolicy: IfNotPresent
        name: centos
        resources: {}
